version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mini_supermarket_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: QuanLySieuThi
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mini_supermarket_network

  app:
    build: .
    container_name: mini_supermarket_app
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mini_supermarket_network

volumes:
  mysql_data:

networks:
  mini_supermarket_network:
    driver: bridge 