# Default configuration for local development
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/QuanLySieuThi?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    # Bật lại Spring Security
    enabled: true
    user:
      # Tắt user mặc định của Spring Security
      name: 
      password: 
      roles: 
    # Cấu hình cho BCrypt password encoder
    password:
      encoder:
        strength: 12  # Độ mạnh của BCrypt (từ 4-31, mặc định là 10)
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
          facebook:
            client-id: test
            client-secret: test
            scope:
              - email
              - public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v3/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          facebook:
            authorization-uri: https://www.facebook.com/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,first_name,middle_name,last_name,name,email,verified
            user-name-attribute: id

  # Cho phép circular references tạm thời
  main:
    allow-circular-references: true
  # Tắt auto-configuration cho UserDetailsService
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    doc-expansion: none
    default-models-expand-depth: 1
    default-model-rendering: model
  show-actuator: false
  group-configs:
    - group: "Mini Supermarket API"
      paths-to-match:
        - "/api/**"
        - "/rest/**"
      packages-to-scan:
        - "com.example.mini_supermarket.rest.controller"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-enough-for-hs256}
  expiration: ${JWT_EXPIRATION:86400}  # 24 hours in seconds

# OAuth2 Frontend Integration - Redirect to Swagger after OAuth2
oauth2:
  frontend:
    base-url: ${FRONTEND_URL:http://localhost:8080}
    success-path: ${OAUTH2_SUCCESS_PATH:/swagger-ui/index.html}
    failure-path: ${OAUTH2_FAILURE_PATH:/swagger-ui/index.html}


#Google
#spring.security.oauth2.client.registration.google.client-id= 12
#spring.security.oauth2.client.registration.google.client-secret= 12

#Facebook
#spring.security.oauth2.client.registration.facebook.client-id=4130
#spring.security.oauth2.client.registration.facebook.client-secret=23
