# Docker environment configuration
spring:
  datasource:
    url: jdbc:postgresql://test-db-postgresql.ns-60uqzq2v.svc:5432/quanlysieuthi
    username: postgres
    password: h5d9q29x
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate  # Validate schema (tables created by init.sql)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true xc